- name: Setup Red Windows Accounts and Passwords
  hosts: windows
  vars:
    password:
      default: Cdt.red!
    users:
      standard:
        - Bill Demirkapi
        - Connor Jackson
        - Dan Benedetti
        - Dennis Palad
        - Jacob Ross
        - James Hassel
        - Keira Carrington
        - Michael Nee
        - Nick Blanock
        - Nuzhat Minhaz
        - Phuong Anh Nguyen
      admin:
        - A Bill Demirkapi
        - A Connor Jackson
        - A Dan Benedetti
        - A Dennis Palad
        - A Jacob Ross
        - A James Hassel
        - A Keira Carrington
        - A Michael Nee
        - A Nick Blanock
        - A Nuzhat Minhaz
        - A Phuong Anh Nguyen

  tasks:
    - name: Configure standard '{{ users.standard }}' account
      win_user:
        fullname: "{{ item }}"
        name: "{{ item }}"
        password: "{{ password.default | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      loop: "{{ users.standard }}"

    - name: Configure administrator '{{ users.admin }}' account
      win_user:
        fullname: "{{ item }}"
        name: "{{ item }}"
        password: "{{ password.default | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        groups:
          - Administrators
          - Users
      loop: "{{ users.admin }}"