---
# CDT-2221 Alpha Red Team
# Anthony Swierkosz; ajs2576
# Adds red team users.

- name: Setup Red Linux Accounts and Passwords
  hosts: linux
  become: yes
  vars:
    password:
      default: Cdt.red!
    users:
      standard:
        - Bill Demirkapi
        - Connor Jackson
        - Dan Benedetti
        - Dennis Palad
        - Jacob Ross
        - James Hassel
        - Keira Carrington
        - Michael Nee
        - Nick Blanock
        - Nuzhat Minhaz
        - Phuong Anh Nguyen
      admin:
        - A Bill Demirkapi
        - A Connor Jackson
        - A Dan Benedetti
        - A Dennis Palad
        - A Jacob Ross
        - A James Hassel
        - A Keira Carrington
        - A Michael Nee
        - A Nick Blanock
        - A Nuzhat Minhaz
        - A Phuong Anh Nguyen

  tasks:
    - name: Configure standard '{{ users.standard }}' account
      user:
        name: "{{ users.standard }}"
        password: "{{ password.default | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      loop: "{{ users }}"


    - name: Configure administrator '{{ users.admin }}' account
      user:
        name: "{{ users.admin }}"
        password: "{{ password.default | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        group: "{{ 'wheel' if ansible_facts['distribution'] == 'CentOS' else 'sudo' }}"
      loop: "{{ users }}"

    - name: Ensure Sudo Package is Present
      package:
        name: sudo
        state: present

    - name: Ensure SSH Package is Present
      package:
        name: ssh
        state: present

- name: Setup Blue Windows Accounts and Passwords
  hosts: windows
  become: yes
  vars:
    password:
      default: Cdt.red!
    users:
      standard:
        - Bill Demirkapi
        - Connor Jackson
        - Dan Benedetti
        - Dennis Palad
        - Jacob Ross
        - James Hassel
        - Keira Carrington
        - Michael Nee
        - Nick Blanock
        - Nuzhat Minhaz
        - Phuong Anh Nguyen
      admin:
        - A Bill Demirkapi
        - A Connor Jackson
        - A Dan Benedetti
        - A Dennis Palad
        - A Jacob Ross
        - A James Hassel
        - A Keira Carrington
        - A Michael Nee
        - A Nick Blanock
        - A Nuzhat Minhaz
        - A Phuong Anh Nguyen

  tasks:
    - name: Configure standard '{{ users.standard }}' account
      win_user:
        fullname: "{{ users.standard }}"
        name: "{{ users.standard }}"
        password: "{{ password.default | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      loop: "{{ users }}"

    - name: Configure administrator '{{ users.admin }}' account
      win_user:
        fullname: "{{ users.admin }}"
        name: "{{ users.admin }}"
        password: "{{ password.default | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        groups:
          - Administrators
          - Users
      loop: "{{ users }}"
