---
# Anthony Swierkosz (ajs2576)
# CDT-2221 - Team A
# Install IIS on Windows Servers

- name: Install IIS on Windows Server
  hosts: iis_servers

  tasks:

    - name: Test Reachability
      ansible.windows.win_ping:

    # Install the IIS Web-Server feature
    # Include sub features and the management tools
    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature

    # Reboot the system if the new feature needs a reboot to work
    - name: Reboot If Required
      ansible.windows.win_reboot:
      when: win_feature.reboot_required